name: Trigger auto deployment for swiftfiddle-runner-functions-402

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swiftfiddle-runner-functions-402-AutoDeployTrigger-4b89bf2b-317f-4915-bddb-9b5dcd027cb0.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS402_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: swiftfiddle.azurecr.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS402_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS402_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-402
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle.azurecr.io/swiftfiddle-runner-functions-402:latest
